# -*- coding: utf-8 -*-
"""TFWID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q9U0zrK4qAzMFPfJHsD1JUmtvf1mz1Gd
"""

import time

class TFWID:
    def __init__(self, min_support):
        self.min_support = min_support
        self.itemsets = {}

    def check_same_equivalence(self, c_i, c_j):
        if len(c_i.itemsets) == 1 and len(c_j.itemsets) == 1:
            return True
        else:
            i = 0
            j = 0
            flag = True
            while i < len(c_i.itemsets) - 1 and j < len(c_j.itemsets) - 1:
                if c_i.itemsets[i] != c_j.itemsets[j]:
                    flag = False
                    break
                i += 1
                j += 1
            return flag

    def diffset_combination(self, a, b, hash_tw_of_trans, sum_tw):
        result = {}
        for b_key, b_value in b.items():
            diff = True
            for a_key, a_value in a.items():
                if b_key == a_key:
                    diff = False
                    break
            if diff:
                result[b_key] = b_value
                sum_tw += hash_tw_of_trans[b_key]
        return result

    def add_transaction(self, transaction):
        for item, weight in transaction:
            if item in self.itemsets:
                self.itemsets[item] += weight
            else:
                self.itemsets[item] = weight

    def generate_itemsets(self):
        frequent_itemsets = []
        for item, support in self.itemsets.items():
            if self.min_support is not None and support >= self.min_support:
                frequent_itemsets.append(([item], support))
        frequent_itemsets.sort(key=lambda x: x[1], reverse=True)
        return frequent_itemsets

    def get_top_k_itemsets(self, k):
        frequent_itemsets = self.generate_itemsets()
        return frequent_itemsets[:k]


def tfwid_candidate_generation(candidate_k, hash_tw_of_trans, ttw):
    candidate_next = []
    for i in range(len(candidate_k) - 1, 0, -1):
        c_i = candidate_k[i]
        for j in range(i - 1, -1, -1):
            c_j = candidate_k[j]
            c = TFWID(None)
            if c.check_same_equivalence(c_i, c_j):
                sum_tw = 0.0
                if len(c_i.itemsets) != 1 and len(c_j.itemsets) != 1:
                    c.itemsets = c.diffset_combination(c_i.itemsets, c_j.itemsets, hash_tw_of_trans, sum_tw)
                else:
                    c.itemsets = c.diffset_combination(c_j.itemsets, c_i.itemsets, hash_tw_of_trans, sum_tw)
                candidate_next.append(c)
    return candidate_next


# Thực hiện đo thời gian chạy trên tập dữ liệu benchmark
def measure_running_time(benchmark_dataset, hash_tw_of_trans, ttw):
    start_time = time.time()

    # Tạo đối tượng TFWID và thêm các transaction vào
    tfwid = TFWID(None)
    for transaction in benchmark_dataset:
        tfwid.add_transaction(transaction)

    # Thực hiện tfwid_candidate_generation và lấy kết quả
    candidate_k = tfwid.generate_itemsets()
    result = tfwid_candidate_generation(candidate_k, hash_tw_of_trans, ttw)

    end_time = time.time()
    running_time = end_time - start_time

    return running_time, result


# Hàm đo thời gian chạy
def measure_running_time(benchmark_dataset, hash_tw_of_trans, ttw):
    start_time = time.time()

    # Tạo đối tượng TFWID và thêm các transaction vào
    tfwid = TFWID(None)
    for transaction in benchmark_dataset:
        tfwid.add_transaction(transaction)

    # Thực hiện tfwid_candidate_generation và lấy kết quả
    candidate_k = tfwid.generate_itemsets()
    result = tfwid_candidate_generation(candidate_k, hash_tw_of_trans, ttw)

    end_time = time.time()
    running_time = end_time - start_time

    return running_time, result

# Tập dữ liệu benchmark
benchmark_dataset = [
    [(1, 0.5), (2, 0.8), (3, 0.3)],
    [(2, 0.6), (4, 0.7)],
    [(1, 0.4), (3, 0.2), (4, 0.9)],
    [(2, 0.7), (3, 0.5), (4, 0.3)],
    [(1, 0.2), (2, 0.4), (3, 0.6)],
    [(1, 0.3), (3, 0.5)],
    [(2, 0.9), (3, 0.3), (4, 0.7)],
]

# Hash table và ttw
hash_tw_of_trans = {
    1: 0.5,
    2: 0.8,
    3: 0.3,
    4: 0.7
}
ttw = 0.0

# Đo thời gian chạy
running_time, result = measure_running_time(benchmark_dataset, hash_tw_of_trans, ttw)

# In thời gian chạy
print("Running time:", running_time, "seconds")

# In kết quả
for c in result:
    print(c.itemsets)

